### ISSUE TITLE
connection always lost

### ISSUE THREAD

**Issue by AlexKash500** [richibrics/PyMonitorMQTT#12]
Yesterday scrip was working correctly but today there are messages:

![image](https://user-images.githubusercontent.com/69472472/98592841-542ba880-22e3-11eb-866a-8e4674a4af02.png)

what is the problem?
Please help

**Comment by richibrics** [comment]
Check if you opened the script twice, because if you are connecting simultaneously to a server that allows only a single connection from a client, then it disconnects you.

**Comment by richibrics** [comment]
Check if you opened the script twice, because if you are connecting simultaneously to a server that allows only a single connection from a client, then it disconnects you.

**Comment by AlexKash500** [comment]
You are absolutely right. thanks a lot

**Comment by richibrics** [comment]
Nice !
