### ISSUE TITLE
brightness command

### ISSUE THREAD

**Issue by AlexKash500** [richibrics/PyMonitorMQTT#13]
when I published brightness_set I have error
![image](https://user-images.githubusercontent.com/69472472/99309695-e515fd00-286a-11eb-809c-93474e3c8fd0.png)

Is it possible to use brightness sensor for get and set monitor brightness ?

**Comment by richibrics** [comment]
With last commit I've just added a thread security check, so I may have solved it. Try it and let me know
PS: set topic has changed to brightness/set

**Comment by AlexKash500** [comment]
yes. It is working now. 
but question 

I added input_number for brightness and 2 automatisations in HA.

- alias: Set lenovo_kitchen_brightness slider
  trigger:
    platform: mqtt
    topic: monitor/PC_NAME/brightness/get
  action:   
    - service: input_number.set_value
      data:
        entity_id: input_number.lenovo_kitchen_brightness
        value: "{{ trigger.payload }}"
     
- alias: lenovo_kitchen_brightness slider moved
  trigger:
    platform: state
    entity_id: input_number.lenovo_kitchen_brightness
  action:
    service: mqtt.publish
    data:
      topic: 'monitor/PC_NAME/brightness/set'
      retain: true
      payload: "{{ states('input_number.lenovo_kitchen_brightness') | int }}"


There is problem - Windows change brightness for monitors after some time (power save mode).
After that brightness restored with minimum brightness. 
Could you help me to change automation or maybe there is another way?
Maybe change brightness sensor to possibility to set brightness with some checks?

**Comment by richibrics** [comment]
Sorry but I didn't understand the problem, don't you want the brightness to be obtained when going into power saving mode ?

**Comment by richibrics** [comment]
Closed due to inactivity
