### ISSUE TITLE
Critical error in 'main.py' at line 49:  list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by DoubyCz** [richibrics/PyMonitorMQTT#14]
I've just followed install instractions in readme, used installed all dependencies, used default yaml.example from this repo and launched "python3 main.py"

`Critical error in 'main.py' at line 49:  list indices must be integers or slices, not str`

_Environment: python 3.8.5 (pip 20.0.2), ubuntu 20.04 lts_

**Comment by richibrics** [comment]
Post here the first 10 lines of your configuration.yaml

**Comment by oferbar** [comment]
I'm getting the same error and I think there is a mismatch in the documentation.
In the readme.md the docs says:

`monitors:
  - broker: example.com
    name: PC_NAME
    port: 1883
    username: example
    password: example
    update_rate: 20 # Seconds
    topic_prefix: example_prefix
    print_topics: False
`

However, the configuration.yaml.example in the code says:

`- broker: 3.122.209.170
  name: 5f685dc02e9d83468db6e0f7
  send_interval: 20 # Seconds

  sensors:
    - Os
    - DesktopEnvironment
`

Neither one is working.

Please advise.

Thanks

**Comment by richibrics** [comment]
I've just updated the .example file, a correct configuration must have `monitors:`  and then the list of brokers.
However it's strange that 

> In the readme.md the docs says:
> 
> `monitors:
> 
> * broker: example.com
>   name: PC_NAME
>   port: 1883
>   username: example
>   password: example
>   update_rate: 20 # Seconds
>   topic_prefix: example_prefix
>   print_topics: False
>   `

returns that error. Are you sure it's the same error ? If not, open a new issue so I can solve both

**Comment by oferbar** [comment]
With the monitors: I'm getting this error:

[ 2020-12-14 11:48:09 |   Info   |  Monitor #1  |            Main           ]  Starting
[ 2020-12-14 11:48:09 |   Info   |  Monitor #1  |            MQTT           ]  Preparing MQTT client
[ 2020-12-14 11:48:09 |   Info   |  Monitor #1  |            MQTT           ]  MQTT Client ready to connect
[ 2020-12-14 11:48:09 |  Error   |     Main     |            Main           ]  Critical error in 'main.py' at line 49: 'send_inte-
                                                                               rval'
[ 2020-12-14 11:48:09 |  Error   |     Main     |            Main           ]  Try to check your configuration.yaml
[ 2020-12-14 11:48:09 |  Error   |     Main     |            Main           ]  If problem persists, check issues (or open a new o-
                                                                               ne) at 'https://github.com/richibrics/PyMonitorMQT-
                                                                               T'
[ 2020-12-14 11:48:09 |   Info   |  Monitor #1  |            MQTT           ]  Connection established

**Comment by richibrics** [comment]
My fault, you have to use 'send_interval' and not 'update_rate'. By the way the correct cofniguration is in the WIKI.
I'm also working on the new website so everything will be better soon.

**Comment by oferbar** [comment]
Now it works 👍 
Still can't see the device in HA...
Is it possible to add another Windows command, like logout?
Thanks

**Comment by richibrics** [comment]
Have you added the custom_component in HA ?
For the new command open a new issue with tags "new command" so I, or whoever who is willing to help, can make it

**Comment by oferbar** [comment]
I can try to add a new command, I have programming experience.
And yes, I added the component to HA, but still having issues.
I'll open a discussion there.
Thanks

**Comment by richibrics** [comment]
Great, in the website there will be for sure a development area to help who is willing to help.
