### ISSUE TITLE
Feature: add sleep command

### ISSUE THREAD

**Issue by apat183** [richibrics/PyMonitorMQTT#2]
Hi, would it be possible to add a sleep or hibernate:

Here is examples for windows:
Sleep (same method as STANDBY, but this command):
`%windir%\System32\rundll32.exe powrprof.dll,SetSuspendState 0,1,0`
Hibernate:
`%windir%\System32\rundll32.exe powrprof.dll,SetSuspendState Hibernate`

Not sure for mac and linux etc. 

Happy to do a pull request, looking at code I'm guessing I just do a new command folder and required code there. Any other changes in other areas required?

**Comment by richibrics** [comment]
Hi 
I'd be happy to be helped to add new commands and sensors. I will wait for your pull request ;).

To add a new Command just create a new folder in Commands folder (e.g. SleepCommand) and place the python file there (use existing commands as examples). Then just link the new file in 'Commands/__ init __.py'.

To enable the new command just write its name in your configuration.yaml file.

Bye
