### ISSUE TITLE
screen in homeassistant

### ISSUE THREAD

**Issue by AlexKash500** [richibrics/PyMonitorMQTT#21]
Cannot find screenshot in home assistant cameras or sensors. But screenshot is present in mqtt. Maybe I need to add something in setting to see screenshot

**Comment by richibrics** [comment]
Can you post your configuration please ?  (first remove any username/password/private data)

**Comment by AlexKash500** [comment]
logger:
  logger_message_width: 70
  file_level: 3
  console_level: 4

monitors:
  - broker: 192.168.2.150
    name: laptop_kitchen
    send_interval: 20 # Seconds
    username: 
    password: 
    
    advanced_information: True # Set to False to receive less data

    discovery:
      enable: True
      preset: homeassistant
      discover_prefix: homeassistant # prefix of config topic, this is the default value of homeassistant
      name_prefix: True # To add the computer name in front of sensors and switches name
      publish_interval: 30

    sensors:
      - State # Important to send availability information
      - Os
      - Ram
      - Disk
      - Cpu
      - Battery
      - CpuTemperatures
      - Network
      - DesktopEnvironment: # When the software returns "base", it's better for you to manually set it
          contents:
            value: base
      - Screenshot

    commands:
      - Shutdown
      - Lock
      - Reboot
      - Sleep
      - Brightness
      - TurnOffMonitors
      - TurnOnMonitors

**Comment by richibrics** [comment]
Do everything else show up in home assistant ?
Check if the screenshot entity logs an error in the log file (or upload the log file here and I'll check for you)

**Comment by AlexKash500** [comment]
[Log.log](https://github.com/richibrics/PyMonitorMQTT/files/6093319/Log.log)
![image](https://user-images.githubusercontent.com/69472472/110172285-f67d1800-7e0d-11eb-89c4-62a3fb7f7461.png)
![image](https://user-images.githubusercontent.com/69472472/110172350-0eed3280-7e0e-11eb-824c-12ee47a2532e.png)

log attached. all parameters from mqtt are in HA

**Comment by richibrics** [comment]
You're right, I tried that entity in my configuration and seems that home assistant skip the camera because there's a wrong payload in the mqtt config message. Let me push the code, I'm back soon

**Comment by richibrics** [comment]
Pull the new changes and try now

**Comment by AlexKash500** [comment]
It is good now. many thanks

**Comment by richibrics** [comment]
Perfect, doing so you're helping improving the system, thanks !
