### ISSUE TITLE
Really not clear what I have to do to get this running

### ISSUE THREAD

**Issue by jacauc** [richibrics/PyMonitorMQTT#22]
Hi @richibrics 

This looks like a really good utility and would love to get it a try, but I had a look at the github site as well as the website, and it is not clear which portions I need to install on Home Assistant, and which needs to run on Windows host?

I tried installing the requirements.txt using Python on the Windows host I want to monitor, but it failed miserably.
![image](https://user-images.githubusercontent.com/18201320/111339609-9180b800-8680-11eb-9e93-7c292066daf0.png)

Also, do I need to install this an addon in Home Assistant, or is it HACS integration? Tried both, neither worked.

I'm specifically looking to use the functionality of hibernating my Windows 10 machine when the Home Assistant UPS sensor detects a power failure. - Or of course manual hibernate/sleep/shutdown/wake up using the HA interface.

Any more guidance on this would be appreciated!

**Comment by richibrics** [comment]
Of course, I have to add that part and fix the requirements for the
different operating systems.

In your case I see there’s a problem with Pillow: it’s currently not
supported on the version of Python you’re using (3.9) so, in the meanwhile
that libraries are being updated, I suggest you to use Python 3.7 or 3.8

Let me know, RB

Il giorno mar 16 mar 2021 alle 16:56 jacauc ***@***.***> ha
scritto:
