### ISSUE TITLE
Feature Request: Example Lovelace YAML

### ISSUE THREAD

**Issue by WeldFire** [richibrics/PyMonitorMQTT#5]
Hello!
Is it possible for you to share an example lovelace YAML file like the frontend that you showcase in the readme?

**Comment by richibrics** [comment]
Certainly, just let me find it and I will add a template file

**Comment by richibrics** [comment]
Check my other repo 'HassMonitorMqtt' that contains the companion component for HomeAssistant; in the last commit I updated the lovelace yaml file with my latest configuration.

**Comment by WeldFire** [comment]
Perfect, thank you!
